### ISSUE TITLE
Wyze Cam v3 T31

### ISSUE THREAD

**Issue by dotslashsuperstar** [OpenIPC/divinus#18]
Does this work on a Wyze Cam v3 (Ingenic T31)?  I keep getting this error...

```
Divinus for ingenic t31 
Chip ID: T31ZX
[watchdog] Watchdog started!
[rtsp] Started listening for clients...
App built with headers v1.0
IMP-1.1.6
---- FPGA board is ready ----
  Board UID : 30AB6E51
  Board HW ID : 72000460
  Board rev.  : 5DE5A975
  Board date  : 20190326
-----------------------------
[media] Creating channel -1 failed with 0xffffffff!
Unknown error code.                                                                                                        
[media] MJPEG initialization failed with 0x1!                                                                              
[hal] Failed to start SDK!
```

**Comment by wberube** [comment]
Good evening! Thanks a lot for the heads-up, I figured out what was causing this! In all honesty, it was quite stable last I have touched the platform and I had never noticed it was broken.

When channel -1 is returned, this means the take_next_free_channel routine (media.c) was unable to find a suitable encoder channel, and it's testing the possibilities until it reaches chnCount (support.c, set to T31_VENC_MAX_CHN), which was equal to zero since there was a break instruction on the loose right before.

Don't hesitate if there's anything I can help you with, and once again, thank you very much!
