### ISSUE TITLE
Why hasn’t the __rtsp_obj_t --> ctx been assigned a value?

### ISSUE THREAD

**Issue by Mike199201** [OpenIPC/divinus#19]
When analyzing the code, I noticed that the seed value used for random number generation in the code, __rtsp_obj_t --> ctx, is not assigned a value. If it is not assigned a value, does it default to 0? If so, would the subsequent calls to __get_random_llu and rand_r functions always generate session_id, rtp_timestamp, and rtp_seq as 0?

**Comment by Mike199201** [comment]
When analyzing the code, I noticed that the seed value used for random number generation in the code, __rtsp_obj_t --> ctx, is not assigned a value. If it is not assigned a value, does it default to 0? If so, would the subsequent calls to __get_random_llu and rand_r functions always generate session_id, rtp_timestamp, and rtp_seq as 0?

**Comment by wberube** [comment]
Good morning!

I am not the author or the librtsp subcomponent, but I have brought in a couple of changes in order to add an audio track which wasn't there initially.

That ctx value is being used to randomize the session IDs provided by the SETUP message and reduce the possible surface for replay attacks, but having to handle two separate set of exchanges for this new second channel complicated things and I haven't invested much resources in reworking this ever since, especially since I plan moving to smolrtsp when time will allow it.
