### ISSUE TITLE
__connection_reset(),session_id is zero

### ISSUE THREAD

**Issue by Mike199201** [OpenIPC/divinus#20]
hello：
Additionally, there may be an issue with the code at __connection_reset(). Assigning `ctx` to 0 and passing it as a parameter to `__get_random_llu` means that `p->session_id` will be 0, which is not a unique value for `session_id`.
![image](https://github.com/user-attachments/assets/80063f34-c16a-41e8-9043-b1ada09783d6)

**Comment by wberube** [comment]
Hi again,

Compared to the previous issue, I have to admit this is probably not very compilant with the RFC standards, the ideal corrective would be to carry the timestamp for both samples when ingesting them from the encoder callback functions, to ensure they get their right presentation time.

I can definitely find some room on my roadmap for this particular timestamp issue, whereas the session ID isn't a big deal right now in my opinion because the RTSP server should NEVER be exposed to the Internet without at least having authentication.

For a business environment, I would most assuredly provide my IP cameras their own subnet just like it used to be done with telephony before SIPS and SRTP became mainstream.

**Comment by wberube** [comment]
I have just provided a fix for this session ID in the commit I pushed minutes ago, hopefully this resolves everything!
