### ISSUE TITLE
How to get /etc/sensors/imx415.bin

### ISSUE THREAD

**Issue by Sunshine-du** [OpenIPC/divinus#21]
![屏幕截图 2024-11-21 145832](https://github.com/user-attachments/assets/a22b3897-88b3-4c7e-a280-3221a01315c4)

**Comment by wberube** [comment]
Good morning! The given configuration sample matches a SigmaStar SSC338Q+IMX415 camera module. HiSilicon chips still need this sensor_config parameter filled, but instead needs a .ini file located under /etc/sensor/config that provides interface and signal processing details instead of a calibration.

**Comment by Sunshine-du** [comment]
Thank you for your reply. I can modify divinus.yaml to point to /etc/sensor/config/imx415_i2c.ini
